#!/bin/bash

set -e

echo "=== Running pre-commit check ==="

diffFiles=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.jsx?$|\.tsx?$' | tr '\n' ' ')
if [ ! -z "$diffFiles" ]; then
  npx eslint $diffFiles
fi

echo "=== Pre-commit check completed successfully ==="
